// app/layout.tsx
import { Manrope } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "sonner";
import Providers from "@/components/Providers";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru" className="">
      <body
        className={`${manrope.className} flex min-h-full flex-col bg-white`}
      >
        <SidebarProvider className="contents">
          <Navbar />
          <main className="flex-grow container mx-auto px-4 py-8">
            <Providers>{children}</Providers>
          </main>
        </SidebarProvider>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
